name: agora_rtc_engine
description: A Flutter plugin for Agora RTC Engine. This plugin provides video and audio communication capabilities.
version: 6.5.1 # Use the version number you want
author: Your Name <your.email@example.com>
homepage: https://github.com/Meeron-2001/Agora-Flutter-SDK

environment:
  sdk: ">=2.12.0 <3.0.0" # Specify the Dart SDK version
  flutter: ">=2.0.0" # Specify the Flutter SDK version

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.agora.agora_rtc_engine
        pluginClass: AgoraRtcEnginePlugin